- README.md
- build.js
- contributing.md
- dev.js
- express-pipeline/babel.config.json
- next-client/src/lib/useSessionStorage.ts
- package.json
Updated the README and added a contributing file.
Went through the README with a fresh repo and caught some bugs. Added a build script as well.
> Brandon readme update + build + bug fixes

- examples/README.md
- examples/reddit_climate_change_posts_500.csv
- express-pipeline/src/pipeline.ts
- next-client/src/features/submission/actions/SubmitAction.ts
* examples/README: quickstart & tips for running a new csv through the pipeline
* console log to confirm that CSV uploading process is running
* don't crash if zero claims are returned from one comment
* lowers default batchSize/parallelism to avoid rate limits (open to discussion)
* Claude model alternative names saved in comment in cofnig
> first PR: ML dev readme, smoother pipeline

- examples/sample_csv_files/pets.csv
- examples/sample_csv_files/tiny.csv
- examples/sample_csv_files/tw_500.csv
- examples/sample_csv_files/tw_76.csv
adds some example csv files for folks to use in testing
> sample csv files: pets 3, tiny 5, AI safety twitter 76 and 500 rows

- examples/notebooks/T3C_LLM_Pipeline_Demo.ipynb
- factor out the T3C LLM pipeline into a Google Colab notebook
- show prompts & track everything in W&B
> W&B tracking and prompts for T3C LLM pipeline

- pyserver/main.py
Adds an id to comment and a commentId field to claims. 
Changes the doc strings as well to reflect these changes.
> Pyserver add comment

- pyserver/config.py
- pyserver/main.py
- pyserver/test_pipeline.py
* standardize all the keys in API responses to `"data"` instead of various different strings
* separate and much cleaner test file :)
* minor fix in managing commentIds
Note: deduplication has gotten worse/changed for me from past tests—not sure what exactly could be happening here yet :)
> [WIP] pyserver cleanup

- .gitignore
- .prettierignore
Merges into #49 
Just a few changes I needed to make while switching to venv
Changed git ignore to exclude pycache and .venv from tracking
Changed prettier ignore to exclude pycache and .venv
> #49 << Venv aux changes

- pyserver/main.py
Merges into #49 
The some previous commit changed the way that config and cute_print was imported. This was causing an issue with me being able to startup the server. I think it would be useful to figure out how we want to handle imports in python. Lets discuss!
> #49 << Pyserver import fix

- common/morphisms/pipeline.ts
- common/schema.ts
- next-client/src/app/global.css
- next-client/src/components/claim/Claim.tsx
- next-client/src/components/copyButton/CopyButton.tsx
- next-client/src/components/elements/button/Button.tsx
- next-client/src/components/outline/Outline.tsx
- next-client/src/components/outline/hooks/useOutlineState.ts
- next-client/src/components/pointGraphic/PointGraphic.tsx
- next-client/src/components/report/Report.tsx
- next-client/src/components/topic/Topic.tsx
- next-client/src/lib/hooks/useTopicTheme.ts
Variety of small UI fixes that were caught in QA.
> Brandon qa fixes

- README.md
- contributing.md
- examples/README.md
MVP for new instructions for running the repo in local dev mode with the Pyserver
TODO
> readme first draft for latest local dev mode

- common/firebase.ts
- next-client/package-lock.json
- next-client/package.json
- next-client/src/app/api/feedback/route.ts
- next-client/src/app/report/[uri]/page.tsx
- next-client/src/assets/icons/index.tsx
- next-client/src/components/elements/dialog/Dialog.tsx
- next-client/src/components/elements/index.ts
- next-client/src/components/feedback/Feedback.tsx
- next-client/src/lib/firebase/firestore.ts
- next-client/src/lib/firebase/serverApp.ts
- next-client/src/lib/types/clientRoutes.ts
Creates a feedback form for users and the backend to do it.
> Feedback mechanism

- next-client/src/app/global.css
- next-client/src/components/barchart/Barchart.tsx
- next-client/src/components/report/Report.tsx
- next-client/src/lib/hooks/useTopicTheme.ts
- next-client/tailwind.config.ts
when the user clicks on a barchart item, it navigates to that topic
barchart now highlights with accent of topic color
> Barchart navigation / colors

- README.md
- contributing.md
- examples/README.md
- corrects venv to .venv
- removes some old instructions
- attempts to clarify about google credentials
> fix venv and condense suggestions across different readmes

- pyserver/main.py
A few pyserver improvements:
* fixes empty subtopics for TS client: any subtopics returned in Step 1 will still exist in Step 2 & 3, with correctly empty lists & counts of claims — this should prevent workers from crashing, and let's watch this area for continued refactoring (we may not want this constraint/behavior in the future — perhaps subtopics derived in Step 1 should be dropped if they have 0 claims
* improves wandb logging: adds prompts & model to each step's summary, renames usage / token count summary vars so we get better overview charts by default in the workspace, more readable/shorter output
* adds a bunch of logic for crux extraction in pyserver — this is not currently exposed as a route and it does work when testing is constrained to pyserver.  Let's figure out if/how/when …
> fix empty subtopics, wandb logging, crux logic

- next-client/src/components/feedback/Feedback.tsx
- next-client/src/components/report/Report.tsx
- next-client/src/components/topic/Topic.tsx
fixed some simple issues where some elements were nested that could cause some hydration bugs
> Small hydration bugs fix

- next-client/src/app/layout.tsx
- pyserver/config.py
- pyserver/main.py
- cleaner wandb logging, easier to configure for local-mode-only
- json loading in try-except — see if this is part of the trouble with some csvs
- tiny layout fix to change text on tab in browser
> logging, json, layout

- next-client/src/components/reportProgress/ReportProgress.tsx
switch statement covers all status cases
> progress report status covers all possible cases

- next-client/src/components/create/CreateReport.tsx
- next-client/src/components/landing/Landing.tsx
Small updates to landing page content, & adding the right example CSV to the create report page
> fix landing page language, link to correct CSV template in create flow

- next-client/src/components/landing/Landing.tsx
> Homepage swap taglines

- next-client/src/components/landing/Landing.tsx
- next-client/src/features/submission/actions/SubmitAction.ts
let's be a bit more conservative with form inputs — fine to keep logging only if we overwrite the sensitive fields
> reduce logging

- next-client/src/components/navbar/Navbar.tsx
- next-client/src/components/navbar/components/LoginButton.tsx
- next-client/src/components/navbar/components/NavbarButtons.tsx
Quick fix to get mobile closer to parity
> Hide hamburger menu button, and add buttons to header, until we have a menu that the hamburger button shows

- next-client/src/components/create/CreateReport.tsx
- next-client/src/features/submission/actions/SubmitAction.ts
Users now need to signin to make a report. Enforced on both client and backend.
> Brandon signin required

- next-client/src/components/create/CreateReport.tsx
- adds a section to direct users to small sample synthetic CSVs so they don't have to make their own files
- removes redundant mention of contacting us
> show small reference datasets

- common/schema.ts
- next-client/src/app/api/report/download/[uri]/route.ts
- next-client/src/app/report/[uri]/page.tsx
- next-client/src/components/report/Report.tsx
I added a button to the toolbar (temp placement) that downloads the report data for the user.
Waiting on designs for where the button should be placed before the PR is ready.
> Download JSON button

- express-server/src/pipeline/claimsStep.ts
- express-server/src/pipeline/cruxesStep.ts
- express-server/src/pipeline/sortClaimsTree.ts
- express-server/src/pipeline/topicTreeStep.ts
we're going with
- no trailing slashes in pyserver/main.py FastAPI routes
- yes trailing slashes in express-server/src/pipeline/[API request to pyserver]
> No trailing slashes

- express-server/src/pipeline/claimsStep.ts
- express-server/src/pipeline/cruxesStep.ts
- express-server/src/pipeline/sortClaimsTree.ts
- express-server/src/pipeline/topicTreeStep.ts
Reverts AIObjectives/tttc-light-js#120 OOPS
> Revert "No trailing slashes"

- express-server/src/pipeline/cruxesStep.ts
- express-server/src/pipeline/sortClaimsTree.ts
- express-server/src/pipeline/topicTreeStep.ts
- try once again to remove the trailing slashes that are breaking prod
- just removing trailing slashes
by staring at them very very intensely
> no very seriously no slashes

- express-server/src/workers.ts
- next-client/src/components/create/CreateReport.tsx
- next-client/src/lib/firebase/config.ts
- pyserver/main.py
- hide extra logs from dev tools view
- just removing/commenting out logs
- works locally with Chrome Dev tools
> prod hotfix: reducing logs

- common/package-lock.json
- common/package.json
- express-server/package-lock.json
- express-server/package.json
- next-client/package-lock.json
- next-client/package.json
hot-fix for api_key_headers branch
Every package.json now explicitly has the same version. 
Red squiggly line go away
> set Zod to be explicitly 3.22.4 to solve infinite depth error

- next-client/src/components/create/CreateReport.tsx
Hides the customize prompts part behind a button on the CreateReport form
CreateReport.tsx
Successfully ran Pets with advanced settings both open and closed, with a change to the prompt, to make sure it works.
> hid customizing prompts behind advanced settings

- common/morphisms/pipeline.ts
- common/package-lock.json
- common/package.json
- common/tsconfig.json
- express-server/package-lock.json
- express-server/package.json
- express-server/src/Firebase.ts
- express-server/src/Queue.ts
- express-server/src/googlesheet.ts
- express-server/src/middleware.ts
- express-server/src/pipeline.ts
- express-server/src/routes/create.ts
- express-server/src/routes/generate.ts
- express-server/src/routes/report.ts
- express-server/src/utils.ts
- express-server/src/workers.ts
- express-server/tsconfig.json
- next-client/package-lock.json
- next-client/package.json
- next-client/tsconfig.json
Make it so we're using strict:true on the express-server, which makes type-checking stronger 
Changed ts-config in express/common to use strict:true, changed places in code that started to throw type errors.
Note: in some places I used ts-ignore, which is generally not good practice, but those places desperately need refactor / would have been a headache to do. 
Ran pets
> Express server strict mode

- next-client/src/components/create/CreateReport.tsx
Title
CreateReport.tsx
Ran a report with custom instructions - works
> hotfix for fixing submit button disable status

- .husky/pre-commit
Fixes the issue where the precommit hook was running after completing the commit
just the husky sh file
Ran a bunch of test commits with both files that get formatted and those that don't
> fixed husky hook so that it runs before committing

- express-server/src/error.ts
- express-server/src/routes/create.ts
- express-server/src/storage.ts
- express-server/src/types/context.ts
- express-server/src/types/result.ts
- express-server/src/workers.ts
This adds the ability to run both public and private google buckets. However, it does not implement the ability to add or read from the private bucket yet. 
Refactored storage.ts to use an abstract storage class and a bucket class
Ran a report manually.
> Private gbuckets

- next-client/src/app/layout.tsx
fixes bug that causes next client to crash
layout.ts
dev
> fixed bug in metadataBase param in layout.ts metadata

- next-client/next-env.d.ts
- next-client/src/components/landing/Landing.tsx
nextjs upgrade meant that next/image needed to be turned to its legacy version
see the diff
nothing crashed
> ran nextjs upgrade codemod for changing next/image to legacy version

- express-server/src/routes/create.ts
Restore default value of gpt-4o-mini to default LLM config.
express-server config data
Locally with sample data.
> T3C-134: Add model back to default config

- .gitignore
Ignore python virtual environments in git by default.
.gitignore
Locally.
> T3C-135: Git ignores any .venvs by default.

- .dockerignore
- docker-compose.yml
- express-server/Dockerfile
- next-client/Dockerfile
- pyserver/Dockerfile
Adjust layer ordering for clarity
Adjust settings like non-root user
To fix tttc-common path issues keeping dockerized next-client from starting correctly.
Docker configs.
Report generation in staging.
> T3C-154: Update docker configs to reflect new paths

- common/morphisms/pipeline/tests/pipeline.test.mts
- common/morphisms/tests/tree-metrics.test.mts
- next-client/package-lock.json
- next-client/package.json
- next-client/vitest.config.mts
Address some simple errors in the test suite due to imports and paths.
common and next-client test suites
Local test suite runs, local test report.
> T3C-139: Fix test failures in common and next-client

- express-server/package.json
- express-server/src/server.ts
Potential fix for [https://github.com/AIObjectives/tttc-light-js/security/code-scanning/1](https://github.com/AIObjectives/tttc-light-js/security/code-scanning/1)
To address the issue, we will introduce rate limiting to the application using the `express-rate-limit` package. This middleware will restrict the number of requests a client can make to the `create` endpoint within a specified time window. Specifically:
1. Install the `express-rate-limit` package.
2. Configure a rate limiter with appropriate settings (e.g., a maximum of 100 requests per 15 minutes).
3. Apply the rate limiter to the `create` route.
This fix ensures that the `create` endpoint is protected against abuse while maintaining its functionality.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before …
> Potential fix for code scanning alert no. 1: Missing rate limiting

- express-server/package-lock.json
- next-client/package-lock.json
Address most of our Dependabot security alerts, prompted by vitest
package-lock.jsons 
Local report generation.
> T3C-40: Run npm audit fix, mostly for vitest dependencies

- express-server/src/routes/create.ts
fix regression on empty speaker names
modified check for empty interview so we provide an anonymous name when interview is ''
with a bunch of local files
> T3C-213: Check for empty string interview column values correctly and return anon name

- README.md
- common/firebase/index.ts
- express-server/src/server.ts
- express-server/src/types/context.ts
- next-client/src/lib/firebase/firestore.ts
Use only "development" or "production" for NODE_ENV
References to NODE_ENV across the repo
Minor formatting near one usage
Local report generation
> T3C-211: Standardize NODE_ENV values

- next-client/src/components/report/hooks/useReportState/path.ts
Change mapIdsToPath to avoid deeply nested calls related to a performance issue.
next-client, useReportState
Locally and staging, with browser profiler.
> T3C-219: Mitigate scaling concern in mapIdsToPath

- common/firebase/index.ts
- common/tsconfig.json
- express-server/src/server.ts
- next-client/src/components/report/hooks/useReportState/path.ts
- next-client/src/lib/firebase/firestore.ts
Restore standard formatting to the repo after my previous changes drifted.
Several files across all modules.
Local report generation.
> T3C-239: Run npm run format for previous changes

- next-client/src/lib/firebase/clientApp.ts
- next-client/src/lib/firebase/config.ts
- next-client/src/lib/firebase/serverApp.ts
Change next-client's Firebase config from buildtime to runtime so we don't need to specify those environment variables during the build using values for production.
next-client firebase config
Local report browsing and generation
> T3C-249: Change Firebase config from buildtime to runtime

- next-client/src/components/claim/Claim.tsx
- next-client/src/components/claim/HoverQuoteCard.tsx
- next-client/src/components/claim/QuoteCard.tsx
- next-client/src/components/claim/__stories__/Claim.stories.tsx
- next-client/src/components/claim/index.ts
- next-client/src/components/node/NodeWrapper.tsx
- next-client/src/components/pointGraphic/PointGraphic.tsx
- next-client/src/components/subtopic/Subtopic.tsx
Refactors the claim component to use more ssr. Cleans up some of the component as well.
> T3C-247 refactored claims component

- docker-compose.yml
- next-client/Dockerfile
- next-client/next.config.js
Fixes the absurd size and build time of our next-js image. Also should address build times for our other images.
Docker files and docker-compose
> T3C-147 fixed large next-client docker size

- examples/sample_csv_files/test_data/test_hard_cases_22.csv
- examples/sample_csv_files/test_data/test_pets_3.csv
- examples/sample_csv_files/test_data/test_scifi_10.csv
- add some basic test cases for making sure comments are parsed correctly
- Consolidating and renaming some test CSV files in examples/
- Locally — note that the hard edge cases will cause the pipeline to fail right now because they yield empty subtopics. 
> adding basic test cases in example CSV files

- .gitignore
- next-client/package-lock.json
- next-client/package.json
- next-client/playwright.config.ts
- next-client/playwright/claim.spec.ts
- next-client/playwright/outline.spec.ts
- next-client/playwright/report.spec.ts
- next-client/playwright/subtopic.spec.ts
- next-client/playwright/topic-opened.spec.ts
- next-client/playwright/topic.spec.ts
- next-client/src/components/claim/Claim.tsx
- next-client/src/components/claim/QuoteCard.tsx
- next-client/src/components/copyButton/CopyButton.tsx
- next-client/src/components/outline/Outline.tsx
- next-client/src/components/pointGraphic/PointGraphic.tsx
- next-client/src/components/report/Report.tsx
- next-client/src/components/subtopic/Subtopic.tsx
- next-client/src/components/subtopic/components/ClaimLoader.tsx
- next-client/src/components/topic/Topic.tsx
sets up Playwright and our initial suit of testing. We can always add more tests from here, but I think this is a good start. It's also only setup for local testing. It probably won't work in CI.
next-client/playwright is setup. Also I added some data-testid tags to some of our components. Those are stripped out in prod, so it shouldn't affect anything else.  
The tests pass. Now there's a little more to this. When you run a test suit, you might have 2 or 3 tests fail because of timeout errors. I increased the timeout period, but that only sometimes seems to help. If you're unsure, use `test.only` on the ones that failed your previous run and see if they …
> Playwright tests

- next-client/src/lib/firebase/clientApp.ts
- next-client/src/lib/firebase/config.ts
- next-client/src/lib/firebase/serverApp.ts
Fix an oversight in how credentials get loaded for Firebase client SDK.
next-client firebase utilities.
Report creation locally and in staging with locally built containers.
> T3C-249: Update Firebase client to correctly use runtime config.

- next-client/src/app/api/feedback/route.ts
- next-client/src/app/create/page.tsx
- next-client/src/app/my-reports/page.tsx
- next-client/src/components/create/CreateReport.tsx
- next-client/src/components/feedback/Feedback.tsx
- next-client/src/components/myReports/MyReports.tsx
- next-client/src/components/navbar/Navbar.tsx
- next-client/src/components/navbar/components/LoginButton.tsx
- next-client/src/lib/firebase/auth.ts
- next-client/src/lib/firebase/clientApp.ts
- next-client/src/lib/firebase/config.ts
- next-client/src/lib/firebase/firestoreClient.ts
- next-client/src/lib/firebase/getIdToken.ts
- next-client/src/lib/firebase/serverApp.ts
- next-client/src/lib/hooks/getUser.ts
I have accepted that the Next config should be set at build time but tried to keep some of the improvements made along the journey.
next-client firebase config, user handling, and related cascading changes. Mostly a reversion to the previous state, but not exactly.
Local and staging report creation.
> T3C-249: Revert to build-time Firebase config

- next-client/src/components/claim/ClaimItem.tsx
- next-client/src/components/subtopic/Subtopic.stories.tsx
- next-client/src/components/subtopic/Subtopic.tsx
- next-client/src/components/subtopic/components/ClaimLoader.tsx
- next-client/src/components/topic/Topic.tsx
Did some cleanup and refactoring on the subtopic component. This should be closer to NextJS's SRR / CSR model and should hopefully speed things up.
Storybook/Chromatic + Playwright tests. There shouldn't be any visual changes or regressions.
> Subtopic refactor

- express-server/src/routes/report.ts
- express-server/src/storage.ts
- next-client/src/app/report/[uri]/page.tsx
Additional logging and comments for clarity.
Reports with filenames with spaces or other encoded characters weren't loading correctly due to a double-encoding bug. This fixes that and clarifies how and where we encode urls when handling buckets.
The report loading logic across next-client and express-server.
Locally browsing a variety of report conditions.
> T3C-330: Fix url encoding for reports in private buckets

- .github/workflows/deploy-express-server-production.yml
- .github/workflows/deploy-express-server.yml
- .github/workflows/deploy-next-client-production.yml
- .github/workflows/deploy-next-client.yml
- .github/workflows/deploy-pyserver-production.yml
- .github/workflows/deploy-pyserver.yml
- next-client/vitest.config.mts
Just a format pass with npm run format
No functional changes
Local report creation just for completeness.
> Reformatting

- next-client/src/components/elements/dialog/Dialog.tsx
It exposes the overlay props for the dialog on the dialog content component. 
Used it in a different wip branch to make changes to the overlay
> T3C-360 expose dialog overlay props on dialog content

- .gitignore
Make changing between several agentic tools a little easier.
.gitignore
No functional changes to test.
> T3C-381: Ignore agentic context files

- next-client/src/components/elements/textIcon/TextIcon.tsx
- next-client/src/components/topic/Topic.tsx
Fixes the spacing between icons and text in the report and topic headers
> T3C-398 fixed spacing in report and topic headers

- next-client/src/components/topic/Topic.tsx
Fixes an errors with subtopic list that are caused by div tags being nested inside of a p tag
> T3C-401 fixed nested div in p tag error

- express-server/src/server.ts
No rate limiting when running in development mode, for convenience.
express-server rate limiter.
Local report creation.
> T3C-420: Skip rate limiter in development

- DEVELOPMENT.md
- express-server/package-lock.json
- express-server/package.json
- express-server/src/__tests__/cors.test.ts
- express-server/src/__tests__/corsIntegration.test.ts
- express-server/src/__tests__/corsServiceIntegration.test.ts
- express-server/src/__tests__/envValidation.test.ts
- express-server/src/__tests__/userAccount.test.ts
- express-server/src/server.ts
- express-server/src/types/context.ts
- express-server/src/utils/corsConfig.ts
- pyserver/main.py
Adds ALLOWED_ORIGINS env var to both
Set up proper CORS configs for the backends.
express-server and pyserver
New tests and local report creation.
> T3C-438: CORS Configuration for express-server and pyserver

- express-server/src/Firebase.ts
- express-server/src/routes/ensureUser.ts
- next-client/src/app/api/user/ensure/route.ts
- next-client/src/components/navbar/Navbar.tsx
- next-client/src/components/navbar/components/LoginButton.tsx
- next-client/src/lib/firebase/auth.ts
- next-client/src/lib/firebase/ensureUserDocument.ts
- next-client/src/lib/hooks/getUser.ts
This implements the wait-list check when the user tries to log in. If they are wait-listed,  it will immediately log them out and show a modal alerting them.
Changes ensureDocument to return the user object. Will then do the check in the auth logic. 
I made it so one of my emails is wait-listed, and tried to log in. 
> T3C-325 Waitlist implementation

- express-server/package-lock.json
- express-server/package.json
- express-server/src/__tests__/cors.test.ts
- express-server/src/__tests__/helmet-config.test.ts
- express-server/src/__tests__/security-headers-integration.test.ts
- express-server/src/server.ts
- pyserver/main.py
- pyserver/test_security_integration.py
Adds security headers middleware 
express-server and pyserver security settings
Test coverage, local report generation.
> T3C-439: Add security headers middleware

- pyserver/main.py
Removes HTTPSRedirectMiddleware causes issues in CloudRun for pyserver
pyserver config
Local report generation (although this wouldn't trigger the CloudRun issue).
> T3C-465: Remove unneeded HTTPSRedirectMiddleware

- express-server/src/__tests__/validateOpenAIApiKeyHeader.test.ts
- express-server/src/middleware.ts
Add API key header validation
express-server middleware
Test coverage and local report generation
> T3C-437: API key header format validation

- common/csv-security/index.ts
- common/csv-security/sanitize-html.d.ts
- common/tsconfig.json
Address a common module type error during build.
common/csv-security types.
Local build and report generation.
> T3C-472: Fix common csv-security build bug

- express-server/src/Firebase.ts
Enable waitlist for all new user signups.
Firebase new user defaults.
Local testing by changing the flag.
> T3C-469: Enable waitlist for new accounts

- express-server/src/featureFlags/index.ts
Address a TS startup error for express-server
Import cleanup in express-server
Local report generation
> T3C-483: Fix missing FeatureFlagConfig type

- express-server/src/__tests__/userAccount.test.ts
Fix two failing tests that assumed old defaults from before T3C-469
express-server tests
Local test run
> T3C-484: FIx user account tests

- common/csv-security/index.ts
- common/package-lock.json
- common/package.json
Also strict text filter
Addresses some type errors that came up in cicd
common sanitization code
Local tests and report generation.
> T3C-495: Fix sanitize-html type in common

- DEVELOPMENT.md
Make sure developers are installing Husky
Development setup instructions
I read them
> T3C-488 Updates Development instructions to install Husky

- next-client/next.config.js
Adjust outputFileTracingRoot to next-client
next-client config
Local docker build and report generation
> T3C-504: Fix outputFileTracingRoot to next-client

- DEVELOPMENT.md
- common/analytics/__tests__/client.test.ts
- common/analytics/__tests__/environment.test.ts
- common/analytics/__tests__/helpers.test.ts
- common/analytics/__tests__/integration.test.ts
- common/analytics/__tests__/localProvider.test.ts
- common/analytics/__tests__/posthogProvider.test.ts
- common/analytics/__tests__/types.test.ts
- common/analytics/client.ts
- common/analytics/environment.ts
- common/analytics/index.ts
- common/analytics/providers/localProvider.ts
- common/analytics/providers/posthogProvider.ts
- common/analytics/types.ts
- common/package-lock.json
- common/package.json
- express-server/package-lock.json
- express-server/src/__tests__/analytics-integration.test.ts
- express-server/src/analytics.ts
- express-server/src/routes/authEvents.ts
- express-server/src/server.ts
- express-server/src/types/context.ts
Implement an Analytics Provider for both client and server.
This adds an analytics provider than can be initialized either to print to logs or sent to Posthog
Tracked user sign in events using both providers
> T3C-476 Implements analytics using posthog or local printing

- common/tsconfig.json
- express-server/src/analytics.ts
Fix a broken import in common causing a crash in staging
Importing analytics from common
Local build
> T3C-509 Fix broken import from common

- express-server/src/routes/authEvents.ts
Missed another broken import
how common is imported in one package
local build
> T3C-509 Fix another broken import

- .github/workflows/chromatic.yml
- next-client/package-lock.json
- next-client/package.json
- next-client/src/components/outline/Outline.stories.tsx
This integrates Chromatic reviews directly into our CI pipeline. Now when we push with front-end changes, a review in Chromatic will be generated. I however should have it setup to not be blocking on merge. 
Might need to do some adjusting later, since there's not really a good way to test it prior to merge.
> T3C-471: Added chromatic github action

- .github/workflows/deploy-next-client.yml
- .github/workflows/deploy-pyserver-production.yml
- .github/workflows/deploy-pyserver.yml
Add appropriate permissions checks to the workflows that were missing them.
Some GitHub workflows.
No functional changes to test.
> T3C-278: Add permissions to GitHub workflows

- next-client/next.config.js
- next-client/src/app/api/auth-events/route.ts
- next-client/src/app/api/feedback/route.ts
- next-client/src/app/api/user/ensure/route.ts
- next-client/src/lib/firebase/authEvents.ts
- next-client/src/lib/firebase/ensureUserDocument.ts
- next-client/src/lib/hooks/getUser.ts
There are a few weird log lines, this cleans those up
Removes no longer needed webpack nonsense 
Logging in next-client
Locally
> T3C-535 fix some logging bugs

- .github/workflows/ephemeral-cleanup.yml
- .github/workflows/ephemeral-deploy.yml
- deploy/cloudrun/express-server.yaml
- deploy/cloudrun/next-client.yaml
- deploy/cloudrun/pyserver.yaml
Sets up ephemeral environments for developers
Github actions were added and deployment configuration YAML files
In Github Actions over and over again
> T3C-344 On demand dev environments

- deploy/cloudrun/express-server.yaml
- express-server/src/__tests__/analytics-integration.test.ts
- express-server/src/__tests__/featureFlagsIntegration.test.ts
- express-server/src/routes/__tests__/create.csv-security.test.ts
- express-server/src/server.ts
- express-server/src/types/context.ts
Creating a redis rate limiting store unique to each environment
Environment variables and build configs
Ephemeral environment
> T3C-559 Rate limit per environment

- pyserver/main.py
Fix a bug in pyserver where a sanitized input will cause an error
pyserver
Locally.
> T3C-563: Fix AttributeError when prompt injection is detected

- express-server/src/workers.ts
Clean up worker failure logs that included extra data
express-server logging
Locally
> T3C-583: Concise worker logs on job failure

- next-client/src/components/reportProgress/ReportProgress.tsx
Fix issue with progress bar bouncing back and forth
next-client
locally
> T3C-636 Updates progress bar with new status

- express-server/src/queue/providers/googlePubSub.ts
- express-server/src/server.ts
A few minor tweaks after the pubsub changes.
express-server
Locally.
> T3C-634: Minor pubsub fixes

- express-server/src/__tests__/workers.test.ts
- express-server/src/server.ts
- express-server/src/workers.ts
Finish removing unused BullMQ code
Workers is express-server
locally
> T3C-601 Removes legacy BullMQ workers

- next-client/.storybook/miscStories/Colors.stories.tsx
- next-client/package-lock.json
- next-client/src/components/claim/Claim.tsx
- next-client/src/components/claim/__stories__/Claim.stories.tsx
- next-client/src/components/copyButton/CopyButton.tsx
- next-client/src/components/elements/button/Button.tsx
- next-client/src/components/subtopic/Subtopic.stories.tsx
- next-client/src/components/subtopic/Subtopic.tsx
- next-client/src/components/subtopic/components/ClaimLoader.tsx
- next-client/src/components/topic/Topic.tsx
- next-client/src/lib/color/index.ts
- next-client/src/lib/color/types.ts
made subtopics indented into topics, changed copy button icon color, changed quote icon color
> T3C-47 made subtopics indented into topics

- common/apiPyserver/index.ts
- express-server/src/jobs/pipeline.ts
- express-server/src/pipeline/claimsStep.ts
- express-server/src/pipeline/cruxesStep.ts
- express-server/src/pipeline/sortClaimsTree.ts
- express-server/src/pipeline/topicSummariesStep.ts
- express-server/src/pipeline/topicTreeStep.ts
- pyserver/main.py
Adding additional logging to pyserver to help with debugging.
express-server and pyserver.
Locally.
> T3C-643: Additional context for pyserver logs

- common/csv-security/__tests__/csv-security.test.ts
- common/csv-security/index.ts
Extend this to plus and minus symbols as well.
The at-symbol filter was too broad, causing input validation problems for valid input.
common
Local report generation with previously failed input.
> T3C-640: Clarify CSV filtering involving at-symbol
