dist/html.js, src/html.tsx
Before:
After:
@Onurbon I'm going to go ahead and merge this into main so we can get back to Evan, just putting it on your radar
=> Wrap titles in plotly.js pie charts

.gitignore, README.md, package-lock.json, package.json, src/gpt.ts, src/pipeline.ts, src/server.ts, src/test.ts, src/types.ts
@colleenm I haven't tested this yet as I'm waiting to get an anthropic key. 
Overview: 
- I added a new option field `model`
- if `model` starts with `"gpt-"` we use OpenAI's API
- if `model` starts with `"claude-"` we use Anthropic's API
- default model remains gpt-4-turbo
=> support Claude  

pyserver/config.py, pyserver/main.py, pyserver/requirements.txt, pyserver/test_oai.py, pyserver/test_pipeline.py, pyserver/utils.py
adds a basic Python server for the T3C LLM pipeline:
* Step 1: **POST /topic_tree/** : given a list of comments [1] return a tree of topics and subtopics
* Step 2: **POST /claims/**: given a topic tree and one comment at a time [2], extract claims from each comment and return a topic tree with claims placed correctly (including original quote) 
* Step 3: **PUT /sort_claims_tree/**: given a tree with placed claims [3] deduplicate the claims in each subtopic and return a sorted version of the full tree, where most common topics, subtopics, and claims each appear first in their parent branch
TODOS
P0
P1
P2
[1]: format/schema for comment list:
```
class Comment(BaseModel):
text: str
class CommentList(BaseModel):
comments: List[Comment]
```
[2] format/schema for topic tree with comments
``` …
```
=> first pass local pyserver

pyserver/main.py
Merges into #49 
I figured out the issue that I showed @staceysv earlier. Turns out it was due to usage not being in JSON format. I added .model_dump() to it and that fixed the issue.
=> #49 << Pyserver fix

common/apiPyserver.ts, express-server/src/pipeline/pipeline.test.ts, express-server/src/workers.ts, pyserver/main.py
The pyserver api now takes an api key to use for ChatGPT. 
Changes the shape of the third route's parameters so it can take an llm config.
Did a successful full pipeline test, so it should be working.
@staceysv can you make sure your tests still work with this? Idk how you manage your tests and such.
=> Pyserver pass API key

dev.js, pyserver/main.py
When you run dev.js (`npm run dev` from root) it'll initialize the venv environment before starting the pyserver.
This also removes the automatic installation from requirements.txt. I thought about including it, but thought maybe there would be an issue with whether people use pip, pip3, or some other alias? Idk what the best approach for that would be. If you have any suggestions let me know. If we exclude it, we'll probably need to mention that in the README
=> Dev script now spins up venv for pyserver

README.md, contributing.md, examples/README.md
- updates the ML-workflows readme with a quickstart/minimal set of instructions for local development/internal contributors 
- cleans up main Readme sections / headings
- super open to ideas for how we can better separate & focus readmes for a few different needs: 
1) comprehensive accurate overview of T3C, 
2) fastest path to local development for AOI team/passionate external contributors,
3) reasonably balanced level of detail  + time-to-productivity for onboarding folks who want to use AOI for their own projects & not necessarily push to core app
TODO: in contributing.md, cut redundancy with main / ML-workflow readmes and specify any instructions/additional info for external contributors
=> readme restructure

common/apiPyserver.ts, common/morphisms/index.ts, common/morphisms/morphisms.ts, common/morphisms/pipeline.ts, common/morphisms/tree-metrics.ts, common/schema.ts, express-server/src/routes/create.ts, express-server/src/workers.ts, next-client/src/app/about/page.tsx, next-client/src/components/claim/Claim.tsx, next-client/src/components/quote/Quote.tsx, next-client/src/components/report/Report.tsx, next-client/src/components/report/hooks/useReportState.ts, next-client/src/components/subtopic/Subtopic.tsx, next-client/src/components/topic/Topic.tsx, pyserver/main.py, pyserver/test_pipeline.py
WIP Pyserver expects and tracks "speaker" for every comment
For sorting claims/third pipeline step
- accepts "sort" = ["numPeople" | "numClaims"]
- returns "num_claims" and "num_speakers", as well as the list of distinct "speakers", for every topic and subtopic
TODOs:
=> speaker attribution

.gitignore, common/morphisms/pipeline.ts, common/schema.ts, utils/package-lock.json, utils/package.json, utils/src/functions/turboToSchema.ts, utils/src/index.ts, utils/src/scripts/turboToSchemaScript.ts, utils/src/tools/terminal.ts, utils/tsconfig.json
Created a new /utils module where we can house things like scripts.
To run:
- `cd utils`
- `npm i`
- Move your source data (csv), your claims arg (.json), and your topic clustering (.json) into `utils/src/scripts/input`
- `npm run start`
- Follow the CLI instructions and presto!
=> Utils module / Turbo => new schema translation

express-server/src/utils.ts
- for any new report, take current unique filename (defined in utils)
- hash it via sha256 implementation from Evan
- return that as much longer but much harder to guess unique url string
- bucket names are still visible but report ids are not guessable for publicly visible report urls
=> hash unique report titles via sha256

next-client/src/components/barchart/Barchart.tsx, next-client/src/components/outline/Outline.tsx, next-client/src/components/report/Report.tsx
So I've been trying to figure out a better way of handling layout on the report screen. Before the major troubles were the toolbar, outline, and all the pieces clashing together.
Here's what it looks like at full width. There's about an even amount of padding between the right side of the screen and the outline. **An alternative could be to try and make the Report more towards the center of the screen**, let me know what you think.
As the page size decreases, the margins on the side of the report decrease and as the window buts up against the report, it'll shrink while the outline stays the same size.
At the md breakpoint, the outline goes away since it will take up most of the space.
md width
Here's the mobile width. 
mobile width
@colleenm lmk if the outline issues you were having still …
=> Report layout

next-client/src/components/create/CreateReport.tsx
shortcut to keeping alpha launch invite-only by not showing a box where folks can paste keys — open to style/wording improvements! ideally they could instead submit a form describing their use case that would auto-populate their account email & that we could easily review :)
=> Alpha launch placeholder: reach out instead of pasting a key

express-server/src/pipeline/claimsStep.ts
super quick one — this fixes the crash in prod for longer reports by not timing out on the (very long, sequential) claims extraction step
in the future, we should use a messaging queue :)
also this puts the cutoff at 7 mins, which is big enough for my DeepSeek data set and probably not for all reports, so let's keep an eye on this part in the future
=> increase timeout so we don't crash on long reports

common/apiPyserver.ts, common/schema.ts, express-server/src/pipeline/claimsStep.ts, express-server/src/pipeline/cruxesStep.ts, express-server/src/pipeline/sortClaimsTree.ts, express-server/src/pipeline/topicTreeStep.ts, express-server/src/workers.ts, pyserver/config.py, pyserver/main.py, pyserver/utils.py
TLDR: Sum and log the costs and token counts for each step of the LLM pipeline
We already have a "tracker" in workers.ts — I added a quick function to calculate the cost of each pipeline step and actually add that cost, and the associated token counts, to the tracker.
My goal was to implement this quickly — I very much welcome refactoring/cleanup for TS style (ideally as a PR on top of this cc @Brandon-Perry )
* calculate costs in pyserver, using a quick dictionary of prices per model and a utils function for the math (returns -1 if we use a model for which we don't yet store the price)
* return the cost of each LLM pipeline step from pyserver (and log to wandb when relevant)
* return the cost from the TS wrapper for each pipeline step
* in workers.ts, add a helper function that …
=> compute and log cost and tokens for LLM pipeline

next-client/src/components/create/CreateReport.tsx
1. What is the goal of this PR?
- remove some stale "lorem ipsum" placeholder text from an alert dialogue
- meta: make sure I made this PR template correctly
2. What changes does it introduce?
- corrects grammar and replaces "lorem ipsum" placeholder with more useful formatting advice
3. How did you test this PR?
- made sure I can run it locally
- to trigger this modal, try to upload a CSV file with one incorrect column name like the following
```
id,text
1,hello
2,world
```
=> UX text polish: swap placeholder for helpful info; fix price estimate

pyserver/config.py, pyserver/main.py
When testing in local mode:
1. Open pyserver/config.py
2. Set DRY_RUN = True
3. Continue testing as you would normally
- mock OpenAI calls on all pyserver routes (topic_tree, claims, sort_claims_tree, cruxes) so we can test the rest of T3C without paying for LLM calls
- finally lint our Python code reasonably with Ruff
- pyserver only to short-circuit each route & return a fixed mock object instead of calling an LLM, if dry_run is passed or set at the config level 
- works locally!
Ideal next steps for when we have time:
- configure DRY_RUN as the default when testing locally
- configure a clean way to turn "calling external LLM" on when working on …
=> dry_run to save $$/time: skip calls to LLMs, return fixed json

next-client/src/app/layout.tsx
Adds an open graph preview to our next client's metadata so that when its shared on a social media site, it has the correct preview.
root layout of nextjs client
I used a GC plugin to see the previews. Here they are:
**One potential issue: **
The image looks like very top part of the preview image is being clipped. @colleenm How does this look to you? If you want it changed, I think we'll need to change the image itself to be a different aspect ratio. 
Also, I think we should add an open graph preview to each report that's generated. However, I need to change it so that our report data is being fetched server side first. I'm going to throw those tickets …
=> Open Graph for home page. 

common/apiPyserver.ts, examples/sample_csv_files/missing_fields_pets.csv, examples/sample_csv_files/speaker_pets.csv, express-server/src/routes/create.ts, express-server/src/workers.ts, pyserver/config.py, pyserver/main.py, pyserver/utils.py
Currently we fail a whole report if any comment is empty. There's also a regression where we fail in workers.ts if a speaker name is not provided / interview column is empty. This draft PR fixes these issues & unblocks immediate generation of reports for CSVs with missing comments or speakers, but there may be more graceful solutions or other edge cases we don't handle yet.
Also added two of my standard test CSVs to examples/sample_csv_data.
- remove requirement for comments to be at least 1 character in schema.ts since users often upload CSVs with some blank rows (empty "comment" fields)
- check for empty comments in pyserver and only call an LLM on one character or more—NOTE, we may want to …
=> don't fail on empty comments / speakers in input CSVs

common/package-lock.json, common/package.json, express-server/package-lock.json, express-server/package.json, next-client/package-lock.json, next-client/package.json
Vitest has a security advisory, update to latest
Also, should be a devDependency in express-server
package.jsons and package-lock.jsons
Rebased on T3C-139_test_regressions, confirmed same test outcomes. Rebased back to main.
=> T3C-106: Update vitest to latest, make devDependency

express-server/src/server.ts
Fix a staging bug where the new rate limiter wasn't working with CloudRun.
express-server app settings.
Pushed rebuilt containers to staging, confirmed fixed.
=> T3C-155: Fix express-rate-limit 'trust proxy' setting

next-client/chromatic.config.json, next-client/package-lock.json, next-client/package.json, next-client/src/components/pointGraphic/PointGraphic.stories.tsx, next-client/src/components/subtopic/Subtopic.stories.tsx
Adds Chromatic to our project and have it integrate with Storybook.
Now when we're developing on the frontend, we can compare visual diffs to a baseline. 
Also I disabled the stories for Subtopics and PointGraphic because of a breaking bug in them. When those components are refactored I'll add them back in. 
Note: You will need to add a .env file to next-client with CHROMATIC_PROJECT_TOKEN. Unfortunately, it doesn't appear that .env.local is supported, so we need to have an additional env file.
=> T3C-244: Added Chromatic to T3C and integrated with Storybook

next-client/src/app/api/feedback/route.ts, next-client/src/app/create/page.tsx, next-client/src/app/layout.tsx, next-client/src/app/my-reports/page.tsx, next-client/src/components/create/CreateReport.tsx, next-client/src/components/feedback/Feedback.tsx, next-client/src/components/navbar/Navbar.tsx, next-client/src/components/navbar/components/LoginButton.tsx, next-client/src/lib/firebase/auth.ts, next-client/src/lib/firebase/clientApp.ts, next-client/src/lib/firebase/config.ts, next-client/src/lib/firebase/firestoreClient.ts, next-client/src/lib/firebase/firestoreServer.ts, next-client/src/lib/firebase/getIdToken.ts, next-client/src/lib/firebase/serverApp.ts, next-client/src/lib/hooks/getUser.ts
Continuing the work in https://github.com/AIObjectives/tttc-light-js/pull/179 because I missed some things in my testing. We want to be able to build next-client without requiring the Firebase credentials to be specified at that time, but then able to specify them at runtime to the container. 
This led to a rabbit hole of how Firebase is handled differently between the client and admin SDKs, so that the right credentials are dynamically used at the right time in the right places.
next-client firebase handling, both client and server.
Local report generation in dev mode with an environment, successful container build without an environment.
Please add one …
=> T3C-249: Refine firebase usage across client and server

common/package.json, common/tsconfig.json, common/utils/index.ts, express-server/src/jobs/pipeline.ts, express-server/src/routes/create.ts, express-server/src/routes/report.ts, express-server/src/routes/sendError.ts, express-server/src/server.ts, express-server/src/storage.ts, express-server/src/types/context.ts, next-client/src/app/api/report/download/[uri]/route.ts, next-client/src/app/report/[uri]/page.tsx, next-client/src/components/reportProgress/ReportProgress.tsx
This enables buckets to be made default-private.
Use signed URLs generated with appropriate credentials that allow buckets to be default-private. 
Still allow accessing old reports in public buckets.
Restrict access to only our public buckets.
express-server and next-client handling of report status and report data fetching, both the actual generation of signed URLs and making the interaction more RESTful.
Report browsing and creation, locally.
=> T3C-97: Use signed URLs to access buckets

next-client/src/app/layout.tsx
There was a vestigial line of code from ye olden days that was causing a GET request for index.js on every navigation.
=> T3C-332 solve index problem in next client

pyserver/Dockerfile
Locally the python server is running at 8000 but in production is running on port 8080.  This will ensure that local and production environments are running on the same ports.
This changes the port that is being listened on for the Python service.  There should be noticeable effect.  
Ran local docker-compose to ensure that pyserv was listening on port 8000
=> T3C-421 Updates port mapping for production python server

common/prompts/index.ts, pyserver/config.py, pyserver/main.py
Create fewer claims to begin with
Create fewer claims of higher quailty without missing the interesting ones, then more aggressively deduplicate the claims into groups.
Prompts and pyserver logic for prompt handling.
With several medium size reports and manual comparison of claim outputs.
=> T3C-248: Deduplicate claims more aggressively

common/utils/index.ts, express-server/src/__tests__/utils.test.ts, express-server/src/routes/create.ts, express-server/src/utils.ts, next-client/src/features/submission/actions/SubmitAction.ts
Address the difference between default outputs of the csv extractor and the default input format. 
CSV parsing, mostly in express-server via common.
Localy report generation using exports from csv extractor.
=> T3C-327: Allow flexible column names to support CSV extractor
